name: netflix_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  chewie: ^1.7.1
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_login: ^4.2.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
